version: "3"

services:
  django:
    image: local_web
    container_name: local_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GUNICORN_WORKER_NUM=1